"""add allowed_origins

Revision ID: 65f636541bd7
Revises: 71eb096246dd
Create Date: 2026-09-02 18:11:09.121075

"""
import uuid
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '65f636541bd7'
down_revision: Union[str, None] = '71eb096246dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# The actual "added in the db" step for CORS — see
# app/security/cors.py's module docstring. The chat widget lives inside
# the main site's own Next.js app (../frontend, repo root), not a
# separate deployed widget — these are that app's own local-dev origins
# (plain `next dev` on :3000, and this repo's local nginx proxy on
# :8080 — see ../nginx/nginx.local.conf). A real deployed domain gets
# added the same way any other origin does — a direct INSERT,
# documented in README's Phase 6 section — not by editing this
# migration after the fact.
DEFAULT_ORIGINS = ["http://localhost:3000", "http://localhost:8080"]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowed_origins',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origin')
    )
    # ### end Alembic commands ###

    allowed_origins_table = sa.table(
        'allowed_origins',
        sa.column('id', sa.String),
        sa.column('origin', sa.String),
        sa.column('created_at', sa.DateTime),
    )
    now = datetime.now(timezone.utc)
    op.bulk_insert(
        allowed_origins_table,
        [{'id': str(uuid.uuid4()), 'origin': origin, 'created_at': now} for origin in DEFAULT_ORIGINS],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('allowed_origins')
    # ### end Alembic commands ###
