#!/usr/bin/env bash
# Fetches Cloudflare's current published IP ranges
# (https://www.cloudflare.com/ips-v4 / ips-v6) and writes them to
# nginx/cloudflare-ips.d/cloudflare-ips.conf — gitignored, generated,
# included by nginx/nginx.conf (see that file's comment for why this
# exists: real_ip resolution once Cloudflare fronts the server) and
# docs/BUSINESS_RULES.md rule 13 for what breaks silently without it.
#
# Meant to run daily via cron/systemd timer (see docs/DEPLOYMENT.md), and
# once immediately after any fresh deploy — a checkout with no generated
# file yet has no trusted ranges at all, so real_ip has nothing to
# substitute against until this runs. Safe to run as often as you like:
# it's a no-op whenever the fetched list matches what's already on disk,
# and only tests+reloads nginx when something actually changed.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="$REPO_ROOT/nginx/cloudflare-ips.d"
OUT="$OUT_DIR/cloudflare-ips.conf"
mkdir -p "$OUT_DIR"

IPV4="$(curl -fsS --max-time 10 https://www.cloudflare.com/ips-v4)"
IPV6="$(curl -fsS --max-time 10 https://www.cloudflare.com/ips-v6)"

# Sanity-check the response shape before trusting it: Cloudflare's
# endpoint returning an HTML error page, a rate-limit response, or an
# empty body must never silently wipe out the trusted-IP list — that
# would either break real_ip resolution (empty) or, worse, get written
# into the generated file as garbage that fails `nginx -t`. Require every
# non-empty line to look like an IPv4 or IPv6 CIDR range, and require at
# least a handful of ranges back (Cloudflare publishes ~15 v4 + ~7 v6;
# anything drastically smaller than that is itself a sign of a bad
# response, not a real change).
CIDR_RE='^[0-9a-fA-F:.]+/[0-9]{1,3}$'
validate_cidr_list() {
  local list="$1" label="$2" min_lines="$3"
  local count=0
  while IFS= read -r line; do
    [ -z "$line" ] && continue
    if ! [[ "$line" =~ $CIDR_RE ]]; then
      echo "ERROR: unexpected line in Cloudflare's $label response: '$line' — leaving $OUT untouched." >&2
      exit 1
    fi
    count=$((count + 1))
  done <<< "$list"
  if [ "$count" -lt "$min_lines" ]; then
    echo "ERROR: only got $count $label range(s) back (expected at least $min_lines) — leaving $OUT untouched." >&2
    exit 1
  fi
}
validate_cidr_list "$IPV4" "ips-v4" 10
validate_cidr_list "$IPV6" "ips-v6" 3

NEW_OUT="$(mktemp "$OUT_DIR/.cloudflare-ips.conf.XXXXXX")"
trap 'rm -f "$NEW_OUT"' EXIT

{
  echo "# Generated by scripts/update-cloudflare-ips.sh — do not edit by hand."
  while IFS= read -r ip; do
    [ -n "$ip" ] && printf 'set_real_ip_from %s;\n' "$ip"
  done <<< "$IPV4"
  while IFS= read -r ip; do
    [ -n "$ip" ] && printf 'set_real_ip_from %s;\n' "$ip"
  done <<< "$IPV6"
} > "$NEW_OUT"

if [ -f "$OUT" ] && diff -q "$OUT" "$NEW_OUT" > /dev/null 2>&1; then
  echo "Cloudflare IP ranges unchanged — nothing to do."
  exit 0
fi

mv "$NEW_OUT" "$OUT"
trap - EXIT
echo "Updated $OUT: $(echo "$IPV4" | grep -c .) IPv4 + $(echo "$IPV6" | grep -c .) IPv6 Cloudflare ranges."

# Validate + reload — best-effort. nginx normally runs in the `nginx`
# docker-compose service with this directory bind-mounted read-only, but
# this script may also run somewhere without docker access (a bare host,
# CI) — degrade to a warning rather than fail the whole update if reload
# can't be confirmed; the file on disk is still correct either way.
if command -v docker >/dev/null 2>&1 && (cd "$REPO_ROOT" && docker compose ps nginx) >/dev/null 2>&1; then
  if (cd "$REPO_ROOT" && docker compose exec -T nginx nginx -t) 2>&1; then
    (cd "$REPO_ROOT" && docker compose exec -T nginx nginx -s reload)
    echo "nginx config validated and reloaded."
  else
    echo "ERROR: nginx -t failed against the new config — $OUT was updated on disk but nginx was NOT reloaded. Fix before anything else restarts nginx and picks up a bad config." >&2
    exit 1
  fi
else
  echo "NOTE: docker/compose not reachable here — $OUT was updated on disk but not reloaded. Run 'docker compose exec nginx nginx -t && docker compose exec nginx nginx -s reload' wherever nginx is actually running."
fi
